version: '3.4'
services:
  server:
    image: "cernoch/venus-server"
    ports:
     - "8088:8088"
    volumes:
     - "./venus-config:/config"

  upnp:
    image: "victronenergy/venus-docker-upnp:latest"
    network_mode: host
     
  influxdb2:
    image: "influxdb:2.6"
    ports:
     - "8086:8086"
    volumes:
     - "./influxdb2:/var/lib/influxdb2"
